---
- hosts: redis_nodes
  become: yes
  gather_facts: yes
  vars:
    ansible_ssh_private_key_file: "./redis-infra-key.pem"
    ansible_ssh_user: ubuntu
  
  pre_tasks:
    - name: Wait for system to become reachable
      wait_for_connection:
        connect_timeout: 30
        timeout: 300
    
    - name: Test connectivity
      ping:
  
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      retries: 3
      delay: 10
    
    - name: Install Redis
      apt:
        name: redis-server
        state: present
      retries: 3
      delay: 10
    
    - name: Start Redis service
      service:
        name: redis-server
        state: started
        enabled: yes
    
    - name: Test Redis connectivity
      command: redis-cli ping
      register: redis_ping
      retries: 5
      delay: 3
      until: redis_ping.stdout == "PONG"
    
    - name: Display Redis status
      debug:
        msg: "Redis is running and responding to ping"
